# Generated by Django 5.0.4 on 2024-04-18 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CURDOperations', '0002_alter_userdetails_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.TextField(max_length=100)),
                ('address_line2', models.TextField(max_length=100, null=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.BigIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CURDOperations.userdetails')),
            ],
            options={
                'db_table': 'AddressDetails',
            },
        ),
    ]
